# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/improve-diarization-with-llm',
                'doc_host': 'https://russedavid.github.io',
                'git_url': 'https://github.com/russedavid/improve-diarization-with-llm',
                'lib_path': 'improve_diarization_with_llm'},
  'syms': { 'improve_diarization_with_llm.core': { 'improve_diarization_with_llm.core.foo': ( 'core.html#foo',
                                                                                              'improve_diarization_with_llm/core.py')}}}
